-- ==============================================================================
-- PRIME MINISTER MANIFESTO TRACKER - SEED DATA (2014 BJP MANIFESTO)
-- ==============================================================================
-- Instructions: 
-- 1. Go to your Supabase Dashboard -> SQL Editor.
-- 2. Paste this entire script and click "Run".
-- 3. This will insert 13 major promises from the 2014 Manifesto as "Unclear" (Pending Evaluation).
-- 4. They will be marked as published = true so you can immediately see them on your website.
-- ==============================================================================

INSERT INTO public.manifesto_promises (title, description, source_manifesto_year, category, status, verdict_summary, announced_date, announced_situation, fulfilled_details, unfulfilled_details, published, slug)
VALUES
(
    'Track down and bring back Black Money', 
    'We will set up a Task Force to track down and bring back Black Money and proactively engage with foreign governments.', 
    2014, 
    'Economy', 
    'Partially Fulfilled', 
    'A Special Investigation Team (SIT) was immediately constituted, and automatic tax exchange treaties were signed, though direct recovery remains complex.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'A Special Investigation Team (SIT) on Black Money was constituted on the very first day of cabinet formation in May 2014. Signed key international tax compliance agreements including AEOI (Automatic Exchange of Information) and amended treaties with Switzerland and Mauritius.',
    'Despite systemic tax reporting and tracking tools, the actual net amount of offshore black money repatriated directly into public accounts remains highly contested and undisclosed.',
    true, 
    'black-money-task-force-2014'
),
(
    'Ram Temple in Ayodhya', 
    'BJP reiterates its stand to explore all possibilities within the framework of the Constitution to facilitate the construction of the Ram Temple in Ayodhya.', 
    2014, 
    'Culture & Heritage', 
    'Fulfilled', 
    'The temple was constructed following the Supreme Court''s unanimous constitutional verdict in 2019 and inaugurated in 2024.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'Following a historic unanimous constitutional verdict by the Supreme Court of India on November 9, 2019, the Central Government established the Shri Ram Janmabhoomi Teerth Kshetra Trust. Construction commenced shortly after, leading to the official consecration ceremony on January 22, 2024.',
    NULL,
    true, 
    'ram-temple-ayodhya-2014'
),
(
    'Abrogation of Article 370', 
    'BJP reiterates its stand on the Article 370, and will discuss this with all stakeholders and remains committed to the abrogation of this article.', 
    2014, 
    'Governance', 
    'Fulfilled', 
    'Article 370 was constitutionally revoked in August 2019, restructuring the state into two Union Territories.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'On August 5, 2019, Parliament passed a statutory resolution to revoke the special status of Jammu & Kashmir under Article 370. The Parliament concurrently passed the J&K Reorganisation Act, bifurcating the region into the Union Territories of Jammu & Kashmir and Ladakh.',
    NULL,
    true, 
    'abrogate-article-370-2014'
),
(
    'Uniform Civil Code', 
    'BJP believes that there cannot be gender equality till such time India adopts a Uniform Civil Code... BJP reiterates its stand to draft a Uniform Civil Code.', 
    2014, 
    'Governance', 
    'In Progress', 
    'Steps are underway at state levels (such as Uttarakhand passing the UCC in 2024), but national implementation remains under draft.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'Significant momentum has built up with the 22nd Law Commission of India actively soliciting public feedback on UCC drafts. Furthermore, Uttarakhand became the first state to officially pass and implement a Uniform Civil Code in March 2024.',
    'Drafting a singular civil code at the national level faces severe political opposition, cultural sensitivities, and debates regarding religious freedom protections in a diverse democracy.',
    true, 
    'uniform-civil-code-2014'
),
(
    '100 New Smart Cities', 
    'We will build 100 new cities; enabled with the latest in technology and infrastructure.', 
    2014, 
    'Infrastructure', 
    'Partially Fulfilled', 
    'The Smart Cities Mission upgraded existing urban infrastructure in 100 designated cities rather than constructing entirely new ones.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'The Smart Cities Mission was launched in June 2015, selecting 100 cities for urban renewal, installing integrated command centers, sustainable energy grids, smart sewage systems, and modernized transit routes.',
    'The mission transitioned from constructing 100 "new cities" to upgrading existing ones. Critics highlight significant project implementation delays, unequal fund utilization, and slow completion rates across smaller municipalities.',
    true, 
    '100-smart-cities-2014'
),
(
    'Diamond Quadrilateral Bullet Train Network', 
    'BJP will launch a Diamond Quadrilateral project - of High Speed Train network (bullet train).', 
    2014, 
    'Infrastructure', 
    'In Progress', 
    'The Mumbai-Ahmedabad bullet train corridor is under active construction, while other routes remain in pre-feasibility phases.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'Active construction is ongoing for the Mumbai-Ahmedabad High-Speed Rail corridor using Japanese Shinkansen technology. Foundations, elevated viaducts, and undersea tunnels are currently under development.',
    'High land acquisition costs, environmental clearances, and enormous financial outlays have severely delayed the original timeline. Feasibility studies for the Delhi-Kolkata and Mumbai-Chennai lines are complete but work has not begun.',
    true, 
    'diamond-quadrilateral-bullet-train-2014'
),
(
    'Price Stabilisation Fund', 
    'Setting up a Price Stabilisation Fund. Special Courts to stop hoarding and black marketing.', 
    2014, 
    'Economy', 
    'Fulfilled', 
    'The Price Stabilization Fund (PSF) was established in 2014-15 to curb inflation of essential agri-commodities.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'The PSF was set up in 2015 under the Department of Agriculture to regulate volatile prices of essential agri-horticultural commodities like onions, potatoes, and pulses through strategic buffer stocks and distribution.',
    NULL,
    true, 
    'price-stabilisation-fund-2014'
),
(
    'Housing for All by 2022', 
    'Pucca house for every Family by 2022 – equipped with the basic facilities of Toilet, Piped water supply, Electricity and proper Access.', 
    2014, 
    'Social Welfare', 
    'Partially Fulfilled', 
    'Over 40 million affordable houses were constructed under PMAY, though some rural targets were extended past the 2022 deadline.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'The Pradhan Mantri Awas Yojana (PMAY-Urban & Gramin) succeeded in sanctioning and building tens of millions of pucca homes for low-income citizens, fully integrated with Swachh Bharat toilets, Saubhagya power, and Ujjwala gas connections.',
    'While massive urban and rural housing targets were met, rural housing completions fell slightly short of the initial 2022 deadline due to supply chain disruptions and funding delays, prompting an extension to 2024.',
    true, 
    'housing-for-all-2022-2014'
),
(
    '33% Reservation for Women', 
    'BJP is committed to 33% reservation in parliamentary and state assemblies through a constitutional amendment.', 
    2014, 
    'Governance', 
    'Fulfilled', 
    'The Nari Shakti Vandan Adhiniyam was successfully passed by Parliament in September 2023.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'The Constitution (128th Amendment) Bill, or Nari Shakti Vandan Adhiniyam, was passed almost unanimously by both the Lok Sabha and Rajya Sabha in September 2023, reserving one-third of all seats in national and state assemblies for women.',
    NULL,
    true, 
    'womens-reservation-bill-2014'
),
(
    'Implementation of GST', 
    'Bring on board all State governments in adopting GST, addressing all their concerns.', 
    2014, 
    'Economy', 
    'Fulfilled', 
    'The Goods and Services Tax (GST) was officially implemented nationwide on July 1, 2017, unifying India''s tax structure.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'Through extensive negotiations with the GST Council consisting of all state finance ministers, the historic 101st Constitutional Amendment was passed. The nationwide Goods and Services Tax was officially launched at midnight on July 1, 2017.',
    NULL,
    true, 
    'implement-gst-2014'
),
(
    'One Rank One Pension (OROP)', 
    'We will implement One Rank One Pension for the armed forces.', 
    2014, 
    'Defense', 
    'Fulfilled', 
    'OROP was formally implemented in November 2015, with revised pensions and arrears distributed in subsequent phases.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'The Government formally announced the scheme details in November 2015, ensuring equal pension payout to military personnel retiring in the same rank with the same length of service. Multiple iterations and revision payouts occurred in 2022.',
    NULL,
    true, 
    'one-rank-one-pension-2014'
),
(
    'Broadband in Every Village', 
    'Broadband in every village. Wi-Fi facilities in public places and commercial centres.', 
    2014, 
    'Infrastructure', 
    'Partially Fulfilled', 
    'The BharatNet project has connected over 200,000 Gram Panchayats with high-speed fiber, though commercial village access is still expanding.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'The BharatNet project (formerly National Optical Fibre Network) was restructured and accelerated. Over 2 lakh Gram Panchayats (village councils) have been successfully linked to high-speed optical fiber infrastructure.',
    'Although the backend infrastructure has successfully reached the Gram Panchayat level in most states, the retail "last-mile" commercial broadband and Wi-Fi delivery to individual households in remote villages remains uneven.',
    true, 
    'village-broadband-wifi-2014'
),
(
    'Clean Ganga (Namami Gange)', 
    'Ensure cleanliness, purity and uninterrupted flow of the Ganga on priority.', 
    2014, 
    'Environment', 
    'Partially Fulfilled', 
    'The Namami Gange program constructed hundreds of sewage treatment plants, though ecological water purity targets remain partially met.', 
    '2014-04-07',
    'Released in the official BJP 2014 Election Manifesto in New Delhi by PM Candidate Narendra Modi.',
    'The integrated conservation mission "Namami Gange" was launched in June 2014, completing 150+ modernized sewage treatment plants (STPs), deploying river-surface trash skimmers, and setting up real-time water quality monitoring stations.',
    'While industrial pollutant discharges decreased significantly along the main stem of the river, bacterial levels (specifically fecal coliform) and ecological water flow levels in several prominent cities still do not meet swimming standards due to continuous rural domestic runoff.',
    true, 
    'clean-ganga-2014'
),
(
    'Doubling Farmers Income by 2022', 
    'We are committed to doubling the income of farmers by 2022 through cooperative efforts, crop insurance, and market access.', 
    2019, 
    'Agriculture', 
    'Partially Fulfilled', 
    'Direct support PM-KISAN was implemented, but the national targeted doubling of real net agricultural income met severe friction.', 
    '2019-04-08',
    'Released in the official BJP 2019 General Election Manifesto in New Delhi by PM Narendra Modi.',
    'The Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) direct benefit transfer was fully scaled up, delivering ₹6,000 annually to over 11 crore farmers. The Agriculture Infrastructure Fund and Soil Health Cards program improved baseline inputs.',
    'The target to double real net income met hurdles due to rising fertilizer/fuel costs. Furthermore, the three structural marketing farm laws passed in 2020 were officially repealed in 2021 after intense regional farmers'' protests, leaving major market deregulation pending.',
    true, 
    'doubling-farmers-income-2019'
),
(
    'Pension Scheme for Small Traders', 
    'We will launch a pension scheme for all small shopkeepers, retail traders, and self-employed individuals after attaining the age of 60 years.', 
    2019, 
    'Social Welfare', 
    'Fulfilled', 
    'The PM Laghu Vyapari Maan-dhan Yojana pension scheme was approved in the first cabinet meeting of 2019.', 
    '2019-04-08',
    'Released in the official BJP 2019 General Election Manifesto in New Delhi by PM Narendra Modi.',
    'Approved during the first cabinet meeting of the Modi 2.0 government in May 2019. The scheme (PM Laghu Vyapari Maan-dhan Yojana) provides an assured monthly pension of ₹3,000 for retail traders, shopkeepers, and self-employed people upon turning 60.',
    NULL,
    true, 
    'pension-small-traders-2019'
),
(
    'Making India a $5 Trillion Economy', 
    'We will make India the third-largest economy in the world by 2030 and a $5 trillion economy by 2024-25.', 
    2019, 
    'Economy', 
    'In Progress', 
    'India overtook the UK to become the 5th largest global economy, though the $5T target date was shifted due to pandemic delays.', 
    '2019-04-08',
    'Released in the official BJP 2019 General Election Manifesto in New Delhi by PM Narendra Modi.',
    'Sustained capital expenditure (Capex) increases, digital public infrastructure adoption, and corporate tax cuts propelled India to become the world''s fastest-growing major economy, reaching a GDP of approximately $3.9 trillion by 2025.',
    'The specific target date of fiscal year 2024-25 was pushed back by 2-3 years, as the severe economic disruption and lockdowns caused by the COVID-19 pandemic in 2020-2021 temporarily contracted economic output.',
    true, 
    'five-trillion-economy-2019'
),
(
    'Jal Jeevan Mission (Piped Tap Water)', 
    'We will launch a Jal Jivan Mission to ensure piped water supply to all households by 2024 under Nal se Jal scheme.', 
    2019, 
    'Infrastructure', 
    'Partially Fulfilled', 
    'Piped water connections expanded from 17% in 2019 to over 78% of rural households, though complete saturation is in progress.', 
    '2019-04-08',
    'Released in the official BJP 2019 General Election Manifesto in New Delhi by PM Narendra Modi.',
    'Launched in August 2019, the mission aggressively built tap water networks across rural districts. Piped water supply grew dramatically from less than 3.2 crore homes to over 14.5 crore homes.',
    '100% saturation of remote tribal hamlets and arsenic-affected areas fell slightly short of the initial December 2024 deadline due to extreme geographic terrains, leading to extended implementation schedules.',
    true, 
    'jal-jeevan-mission-2019'
),
(
    'National Infrastructure Capital Outlay', 
    'We will make a capital investment of Rs. 100 lakh crore in the infrastructure sector by 2024.', 
    2019, 
    'Infrastructure', 
    'Fulfilled', 
    'The National Infrastructure Pipeline (NIP) was successfully launched with projects worth over Rs. 111 lakh crore.', 
    '2019-04-08',
    'Released in the official BJP 2019 General Election Manifesto in New Delhi by PM Narendra Modi.',
    'The central government established the National Infrastructure Pipeline (NIP) detailing projects across roads, railways, power, and aviation worth Rs. 111 lakh crore. Capital expenditure was aggressively hiked, meeting and exceeding outlay targets.',
    NULL,
    true, 
    'national-infrastructure-pipeline-2019'
),
(
    'One Nation One Election Implementation', 
    'We will work towards implementing One Nation, One Election to conduct simultaneous polls across India.', 
    2024, 
    'Governance', 
    'In Progress', 
    'The High-Level Committee report recommending simultaneous polls was officially accepted by the Union Cabinet in 2024.', 
    '2024-04-14',
    'Released in the official BJP 2024 General Election Sankalp Patra (Modi Ki Guarantee) at Party HQ, New Delhi by PM Narendra Modi.',
    'A high-powered committee led by former President Ram Nath Kovind submitted its final report. In September 2024, the Union Cabinet officially accepted its recommendations for simultaneous Lok Sabha, Assembly, and local body elections.',
    'Actual implementation requires complex constitutional amendments and ratifications by at least 50% of the State Legislatures, which faces strong political debate and federal consensus hurdles.',
    true, 
    'one-nation-one-election-2024'
),
(
    'National Uniform Civil Code', 
    'BJP believes that women cannot get equal rights until India adopts a UCC... We reiterate our stand to draw a Uniform Civil Code.', 
    2024, 
    'Governance', 
    'In Progress', 
    'State-level codes (Uttarakhand UCC passed in 2024) serve as regional frameworks while the national Law Commission draft is active.', 
    '2024-04-14',
    'Released in the official BJP 2024 General Election Sankalp Patra (Modi Ki Guarantee) at Party HQ, New Delhi by PM Narendra Modi.',
    'Supported legislative enactments of state-level Uniform Civil Codes (Uttarakhand passed its UCC in March 2024). The Law Commission of India is actively compiling public and legal inputs for a national draft.',
    'The drafting of a singular national civil code requires resolving intense federal debates, tribal exceptions, and constitutional religious freedom arguments.',
    true, 
    'national-ucc-2024'
),
(
    'Free Electricity via Surya Ghar Scheme', 
    'We will enable homes across the country to get free electricity up to 300 units per month by installing rooftop solar under PM Surya Ghar.', 
    2024, 
    'Social Welfare', 
    'In Progress', 
    'PM Surya Ghar Muft Bijli Yojana was launched with a Rs. 75,021 crore budget to fund 1 crore household installations.', 
    '2024-04-14',
    'Released in the official BJP 2024 General Election Sankalp Patra (Modi Ki Guarantee) at Party HQ, New Delhi by PM Narendra Modi.',
    'Officially approved in early 2024, the program provides upfront direct central subsidies of up to 60-70% to install rooftop solar panels, enabling households to generate up to 300 units of free power monthly.',
    'Reaching the target of 1 crore active solar roofs is in progress as discom net-metering approvals, local installer certifications, and domestic solar cell manufacturing are scaling up.',
    true, 
    'pm-surya-ghar-solar-2024'
),
(
    'Ayushman Bharat Health Cover for Seniors (70+)', 
    'We will expand the Ayushman Bharat PM-JAY cover to provide free quality healthcare to all senior citizens aged 70 years and above.', 
    2024, 
    'Social Welfare', 
    'Fulfilled', 
    'The Union Cabinet officially approved free Ayushman Bharat cover for all senior citizens 70+ regardless of income in 2024.', 
    '2024-04-14',
    'Released in the official BJP 2024 General Election Sankalp Patra (Modi Ki Guarantee) at Party HQ, New Delhi by PM Narendra Modi.',
    'The Union Cabinet chaired by PM Narendra Modi officially approved free health insurance under Ayushman Bharat PM-JAY for all seniors aged 70 and above on September 11, 2024. A distinct card provides ₹5 lakh shared annual cover.',
    NULL,
    true, 
    'ayushman-bharat-70-plus-2024'
),
(
    'Empowering 3 Crore Lakhpati Didis', 
    'We have empowered 1 crore rural women to become Lakhpati Didis. We will now empower 3 crore rural women to become Lakhpati Didis.', 
    2024, 
    'Social Welfare', 
    'In Progress', 
    'Over 1.2 crore rural Self-Help Group (SHG) women have achieved Lakhpati Didi status, with programs active to hit 3 crore.', 
    '2024-04-14',
    'Released in the official BJP 2024 General Election Sankalp Patra (Modi Ki Guarantee) at Party HQ, New Delhi by PM Narendra Modi.',
    'Under the National Rural Livelihoods Mission (DAY-NRLM), micro-loans, drone training (Namo Drone Didi), and marketing support are provided to rural women SHGs. Over 1.2 crore women have officially crossed the ₹1 lakh annual income mark.',
    'Scaling financial tracking and training infrastructure to ensure sustainable earnings for the remaining 1.8 crore rural women is actively undergoing nationwide implementation.',
    true, 
    'lakhpati-didi-shg-2024'
),
(
    'Jammu & Kashmir PM Development Package (PMDP)', 
    'We will execute a comprehensive Prime Minister''s Development Package (PMDP) of Rs. 80,000 crore for the socio-economic development of Jammu & Kashmir, rebuilding infrastructure and restoring livelihoods.', 
    2015, 
    'Infrastructure (J&K)', 
    'Fulfilled', 
    'The massive Rs. 80,000 crore package was fully mobilized, completing flagship tunnels, AIIMS campuses, and power grids.', 
    '2015-11-07',
    'Announced in a public address by PM Narendra Modi at Sher-i-Kashmir Cricket Stadium in Srinagar, Jammu & Kashmir.',
    'The package comprised 63 major projects across road, power, health, tourism, and relief sectors. Over 90% of the funds have been successfully utilized. Major achievements include the operationalization of the Chenani-Nashri Tunnel, Ramban-Banihal road upgrades, and AIIMS campuses at Samba and Awantipora.',
    NULL,
    true, 
    'jk-pm-development-package-2015'
),
(
    'Bihar Special Infrastructure Package', 
    'We will implement a special development package of Rs. 1.25 lakh crore for Bihar covering highways, railways, airports, petroleum, and a second AIIMS in Darbhanga.', 
    2015, 
    'Infrastructure (Bihar)', 
    'Partially Fulfilled', 
    'Highway network and rail grid expansions were delivered, but the flagship second AIIMS in Darbhanga faced long delays.', 
    '2015-08-18',
    'Announced by PM Narendra Modi in a public campaign speech at Ara, Bihar.',
    'Substantial parts of the package were successfully implemented, including the complete electrification of Bihar''s railway grid, high-speed fiber installations across gram panchayats, and extensive national highway expansions led by NHAI (Patna-Gaya, Ara-Pararia).',
    'The landmark second AIIMS hospital in Darbhanga faced extreme implementation delays, stalling construction for years due to land-allocation disputes, bureaucratic friction over low-lying ground suitability, and political disagreements between state and central ministries.',
    true, 
    'bihar-special-package-2015'
),
(
    'Northeast capital city rail connection', 
    'We will connect all eight capital cities of the Northeast states with broad-gauge railway tracks and construct high-speed highway corridors.', 
    2019, 
    'Infrastructure (Northeast)', 
    'Fulfilled', 
    'Capital cities like Agartala, Naharlagun, and Bairabi were connected to the broad-gauge grid, alongside building Bogibeel Bridge.', 
    '2019-04-08',
    'Released in the official BJP 2019 General Election Manifesto in New Delhi by PM Narendra Modi.',
    'Capital cities of Northeast states (including Agartala, Naharlagun/Itanagar, and Bairabi/Aizawl) were linked directly to the national broad-gauge rail grid. The iconic Bogibeel Bridge, India''s longest rail-cum-road bridge crossing the Brahmaputra River in Assam, was commissioned and opened.',
    NULL,
    true, 
    'northeast-rail-connectivity-2019'
),
(
    'Purvodaya Eastern Industrial Hub', 
    'We will launch the Purvodaya initiative to turn Eastern India (West Bengal, Odisha, Jharkhand) into a major economic and steel hub with deep-water ports.', 
    2019, 
    'Economy (East India)', 
    'In Progress', 
    'Paradeep and Haldia Port expansions are complete, though West Bengal industrial corridor land acquisition remains delayed.', 
    '2019-04-08',
    'Announced during PM Narendra Modi''s Eastern India campaign launch in Kolkata, West Bengal.',
    'Secured deep modernization upgrades for the Paradeep Port in Odisha and expansion of the Haldia Dock complex in West Bengal. Established the Kalinganagar steel industrial cluster and linked the region to domestic gas grids under Urja Ganga.',
    'High-speed industrial corridor development in West Bengal faced local administrative deadlocks and land acquisition issues, delaying several planned private-public heavy engineering clusters.',
    true, 
    'purvodaya-eastern-corridor-2019'
),
(
    'Sindhudurg Sea Tourism & Maritime Hub', 
    'We will develop the Konkan coast, especially Sindhudurg, as a world-class sea tourism hub and establish the National Institute of Water Sports.', 
    2019, 
    'Tourism (Maharashtra)', 
    'Partially Fulfilled', 
    'Chipi Airport was opened in 2021 to boost tourism, but integrated resort zoning faced environmental clearance delays.', 
    '2019-10-13',
    'Announced by PM Narendra Modi during a Maharashtra Assembly election campaign rally in Sindhudurg.',
    'The Sindhudurg (Chipi) Airport was successfully constructed and inaugurated for scheduled commercial passenger flights in 2021, and the National Institute of Water Sports was approved to boost local maritime employment.',
    'Developing the area into a massive, integrated global resort ecosystem has been slowed by local environmental coastal zone management (CRZ) laws and delayed regulatory green clearances.',
    true, 
    'sindhudurg-sea-tourism-2019'
),
(
    'National Turmeric Board in Telangana', 
    'We will establish a dedicated National Turmeric Board headquartered in Telangana to support turmeric farmers with pricing and exports.', 
    2023, 
    'Agriculture (Telangana)', 
    'Fulfilled', 
    'The Union Ministry of Commerce officially notified and constituted the National Turmeric Board in October 2023.', 
    '2023-10-01',
    'Announced by PM Narendra Modi during a development project rally at Mahabubnagar, Telangana.',
    'The Union Ministry of Commerce officially notified the constitution of the National Turmeric Board on October 4, 2023, fulfilling the long-standing demands of Nizamabad and Mahabubnagar farming communities to boost export logistics and minimum price support.',
    NULL,
    true, 
    'telangana-turmeric-board-2023'
),
(
    'Balrampur Saryu Canal Irrigation Project', 
    'We will complete the long-delayed Saryu Canal National Project to provide assured irrigation to over 14 lakh hectares of land in Eastern UP.', 
    2021, 
    'Agriculture (UP)', 
    'Fulfilled', 
    'The project, pending for 40 years, was completed and inaugurated by PM Narendra Modi in Balrampur in 2021.', 
    '2021-12-11',
    'Announced and inaugurated by PM Narendra Modi during an official ceremony in Balrampur, Uttar Pradesh.',
    'The massive project, pending for over 40 years under prior administrations, was fast-tracked and completed. PM Narendra Modi officially inaugurated it in December 2021, linking five major rivers to bring assured irrigation to over 29 lakh farmers across 9 districts in Eastern UP.',
    NULL,
    true, 
    'saryu-canal-up-2021'
),
(
    'National Sowa Rigpa Research Institute in Leh', 
    'We will establish the National Institute of Sowa-Rigpa in Leh, Ladakh to preserve, research, and promote the traditional Himalayan medical system.', 
    2019, 
    'Culture & Heritage (Ladakh)', 
    'Fulfilled', 
    'The Union Cabinet officially approved and funded the autonomous research institute post-UT creation.', 
    '2019-11-20',
    'Approved by the Union Cabinet led by PM Narendra Modi following the creation of Ladakh as a Union Territory.',
    'The Union Cabinet officially approved the establishment of the National Institute of Sowa-Rigpa (NISR) as an autonomous research body under the Ministry of AYUSH, locating it in Leh, Ladakh. The institute is fully functional, conducting regional clinical research and traditional academic courses.',
    NULL,
    true, 
    'sowa-rigpa-ladakh-2019'
)
ON CONFLICT (slug) DO NOTHING;
