-- =============================================
-- Script C: NEWS EVENTS TABLE
-- Paste this in Supabase → SQL Editor → New Query → Run
-- This table is the daily "heartbeat" that keeps the free-tier project alive
-- =============================================

-- Stores daily political news generated by the GitHub Actions automation
CREATE TABLE IF NOT EXISTS news_events (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  leader       TEXT        NOT NULL,
  state        TEXT        NOT NULL,
  sentiment_score TEXT,
  ticker_headline  TEXT    NOT NULL,
  blog_title   TEXT,
  blog_content TEXT,
  social_post  TEXT,
  original_url TEXT,
  news_date    DATE        NOT NULL,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Prevent exact duplicate entries for the same leader on the same day
CREATE UNIQUE INDEX IF NOT EXISTS idx_news_leader_date
  ON news_events (leader, news_date);

-- Fast lookups by date (for fetching today's news)
CREATE INDEX IF NOT EXISTS idx_news_date
  ON news_events (news_date DESC);

-- Row Level Security — allow public reads, no public writes
ALTER TABLE news_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read news_events"
  ON news_events FOR SELECT
  USING (true);

-- Only service role (GitHub Actions) can insert/update
-- No anon insert policy = only the server-side automation can write
