import { RajneetiEvent } from "./rajneeti";

export const RAJNEETI_EVENTS: RajneetiEvent[] = [
  {
    id: "ev1",
    stateCode: "DL",
    stateName: "Delhi",
    politicianName: "Narendra Modi",
    partyName: "BJP",
    delta: +4,
    sentiment: "positive",
    avatarColor: "bg-orange-500",
    score: 2060,
    statusLabel: "National Drive",
    summary:
      "Central government announces major infrastructure projects in the capital, boosting regional economic confidence.",
    mainPhrase: "INFRA BOOM",
    shareUrl: "/rajneeti/delhi/bjp/narendra-modi-4",
  },
  {
    id: "ev2",
    stateCode: "UP",
    stateName: "Uttar Pradesh",
    politicianName: "Rahul Gandhi",
    partyName: "Congress",
    delta: +3,
    sentiment: "positive",
    avatarColor: "bg-blue-500",
    score: 1980,
    statusLabel: "Nation Building",
    summary:
      "Opposition unity gains momentum as new alliance strategies are discussed for key UP constituencies.",
    mainPhrase: "ALLIANCE MOMENTUM",
    shareUrl: "/rajneeti/uttar-pradesh/congress/rahul-gandhi-3",
  },
  {
    id: "ev3",
    stateCode: "WB",
    stateName: "West Bengal",
    politicianName: "Mamata Banerjee",
    partyName: "TMC",
    delta: +2,
    sentiment: "positive",
    avatarColor: "bg-green-500",
    score: 2100,
    statusLabel: "Regional Pride",
    summary:
      "New welfare schemes launched in Kolkata receive widespread public support, strengthening regional front visibility.",
    mainPhrase: "WELFARE SURGE",
    shareUrl: "/rajneeti/west-bengal/tmc/mamata-banerjee-2",
  },
  {
    id: "ev4",
    stateCode: "MH",
    stateName: "Maharashtra",
    politicianName: "Uddhav Thackeray",
    partyName: "Shiv Sena",
    delta: -2,
    sentiment: "negative",
    avatarColor: "bg-amber-500",
    score: 2025,
    statusLabel: "Political Shift",
    summary:
      "Internal local body debates over urban planning slightly dampen recent approval gains in Mumbai.",
    mainPhrase: "PLANNING ROW",
    shareUrl: "/rajneeti/maharashtra/ss/uddhav-thackeray-minus-2",
  },
];
